services:
  - type: web
    name: qpixa-app
    runtime: node
    buildCommand: npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        placeholder: "Paste your Supabase Project URL here"
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        placeholder: "Paste your Supabase Anon Key here"
      - key: GEMINI_API_KEY
        sync: false
