import { Post } from './AppContext';

const suffix = "Use the uploaded image as reference. Maintain same face, identity, hairstyle, and facial features. Apply the scene and style accurately. Ultra realistic, high detail, cinematic lighting, 4K quality.";

// Using Pollinations AI with a fixed seed to maintain facial consistency across the generated templates
const getImageUrl = (prompt: string) => `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=800&height=1000&nologo=true&enhance=false&seed=888`;

// Character descriptions to maintain consistency across the template images
// This matches the image you uploaded (Handsome Indian man with thick black beard and stylish hair)
const MALE_DESC = "Handsome Indian man with thick black beard and stylish swept-back hair";
const FEMALE_DESC = "Beautiful Indian woman with long dark hair and sharp facial features";
const BOY_DESC = "Cool young Indian boy with a trendy modern haircut";
const KID_DESC = "Cute Indian kid with a bright smile and big eyes";

export const MOCK_POSTS: Post[] = [
  {
    id: 'mock-1',
    title: 'CSK Fan with Dhoni',
    imageUrl: getImageUrl(`${MALE_DESC} wearing a yellow CSK cricket jersey, taking a selfie with MS Dhoni in the background at a packed cricket stadium`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Wearing a yellow CSK cricket jersey, taking a selfie with MS Dhoni in the background at a packed cricket stadium, cheering crowd. ${suffix}`,
    tags: ['ipl', 'csk', 'dhoni'],
    category: 'IPL 2026',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 45200, likes: 12500, saves: 3400, comments: 890,
    createdAt: new Date(Date.now() - 1000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-2',
    title: 'Red Ferrari Driver',
    imageUrl: getImageUrl(`${MALE_DESC} driving a red Ferrari convertible on a coastal highway at sunset wearing luxury sunglasses`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Driving a red Ferrari convertible on a coastal highway at sunset, wearing luxury sunglasses, wind blowing hair, cinematic lighting. ${suffix}`,
    tags: ['ferrari', 'luxury', 'cars'],
    category: 'Luxury',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 21000, likes: 8900, saves: 1200, comments: 340,
    createdAt: new Date(Date.now() - 2000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-3',
    title: 'Maldives Vacation',
    imageUrl: getImageUrl(`${FEMALE_DESC} relaxing on a tropical beach in Maldives wearing a floral summer dress holding a coconut drink`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Relaxing on a tropical beach in Maldives, wearing a floral summer dress, holding a coconut drink, crystal clear water background. ${suffix}`,
    tags: ['summer', 'beach', 'vacation'],
    category: 'Summer',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 34000, likes: 12000, saves: 3400, comments: 560,
    createdAt: new Date(Date.now() - 3000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-4',
    title: '90s Bollywood Retro',
    imageUrl: getImageUrl(`${FEMALE_DESC} 90s Bollywood retro style wearing a polka dot saree vintage hairstyle dramatic film lighting`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `90s Bollywood retro style, wearing a polka dot saree, classic vintage hairstyle, dramatic film lighting, nostalgic film grain. ${suffix}`,
    tags: ['90s', 'bollywood', 'retro'],
    category: '90s Retro',
    style: 'Vintage',
    aspectRatio: '4:5',
    views: 15000, likes: 6700, saves: 900, comments: 220,
    createdAt: new Date(Date.now() - 4000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-5',
    title: 'Billionaire CEO',
    imageUrl: getImageUrl(`${MALE_DESC} as a Billionaire CEO standing in a luxury high-rise office wearing a tailored navy blue suit night city skyline`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Billionaire CEO standing in a luxury high-rise office, wearing a tailored navy blue suit, city skyline at night through glass window, powerful aura. ${suffix}`,
    tags: ['ceo', 'office', 'luxury'],
    category: 'Professions',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 45000, likes: 21000, saves: 5600, comments: 890,
    createdAt: new Date(Date.now() - 5000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-6',
    title: 'Cyberpunk Street',
    imageUrl: getImageUrl(`${BOY_DESC} Cyberpunk style neon glowing jacket futuristic Tokyo street raining neon lights`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Cyberpunk style, neon glowing jacket, standing in a futuristic Tokyo street raining neon lights, cinematic shadows. ${suffix}`,
    tags: ['cyberpunk', 'neon', 'tokyo'],
    category: 'Fantasy',
    style: 'Cyberpunk',
    aspectRatio: '4:5',
    views: 9800, likes: 3200, saves: 450, comments: 80,
    createdAt: new Date(Date.now() - 6000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-7',
    title: 'RCB Fan in Stadium',
    imageUrl: getImageUrl(`${FEMALE_DESC} wearing red RCB cricket jersey face painted stadium background golden hour lighting`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Wearing red RCB cricket jersey, face painted with team colors, stadium background, golden hour lighting, enthusiastic expression. ${suffix}`,
    tags: ['ipl', 'rcb', 'cricket'],
    category: 'IPL 2026',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 28000, likes: 11000, saves: 2300, comments: 450,
    createdAt: new Date(Date.now() - 7000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-8',
    title: 'Royal Wedding Groom',
    imageUrl: getImageUrl(`${MALE_DESC} as a Royal Indian wedding groom wearing an embroidered golden sherwani floral garland luxury palace`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Royal Indian wedding groom, wearing an embroidered golden sherwani, floral garland, luxury palace background, warm festive lighting. ${suffix}`,
    tags: ['wedding', 'groom', 'royal'],
    category: 'Trending',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 15000, likes: 5800, saves: 1100, comments: 180,
    createdAt: new Date(Date.now() - 8000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-9',
    title: 'Gym Transformation',
    imageUrl: getImageUrl(`${MALE_DESC} with a muscular gym body lifting heavy dumbbells in a dark gritty gym sweat on skin`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Muscular gym body, lifting heavy dumbbells, sweat on skin, dark gritty gym background, dramatic overhead lighting. ${suffix}`,
    tags: ['gym', 'fitness', 'workout'],
    category: 'Trending',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 11000, likes: 4200, saves: 750, comments: 140,
    createdAt: new Date(Date.now() - 9000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-10',
    title: 'Royal Wedding Bride',
    imageUrl: getImageUrl(`${FEMALE_DESC} as a Royal Indian bride wearing a heavy red lehenga traditional gold jewelry soft glowing wedding stage`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Royal Indian bride, wearing a heavy red lehenga, traditional gold jewelry, soft glowing wedding stage background. ${suffix}`,
    tags: ['wedding', 'bride', 'royal'],
    category: 'Trending',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 32000, likes: 14000, saves: 3800, comments: 670,
    createdAt: new Date(Date.now() - 10000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-11',
    title: 'Superbike Rider',
    imageUrl: getImageUrl(`${BOY_DESC} sitting on a black Kawasaki Ninja superbike wearing a leather biker jacket neon city street at night`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Sitting on a black Kawasaki Ninja superbike, wearing a leather biker jacket, neon city street at night, cinematic. ${suffix}`,
    tags: ['bike', 'rider', 'neon'],
    category: 'Luxury',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 18000, likes: 7500, saves: 1200, comments: 280,
    createdAt: new Date(Date.now() - 11000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-12',
    title: 'Dubai Desert Safari',
    imageUrl: getImageUrl(`${FEMALE_DESC} standing in Dubai desert dunes wearing a flowing red dress golden sunset luxury travel`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Standing in Dubai desert dunes, wearing a flowing red dress, golden sunset, luxury travel aesthetic. ${suffix}`,
    tags: ['dubai', 'desert', 'travel'],
    category: 'Summer',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 25000, likes: 9800, saves: 2100, comments: 350,
    createdAt: new Date(Date.now() - 12000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-13',
    title: 'Mafia Don',
    imageUrl: getImageUrl(`${MALE_DESC} as a Mafia boss sitting on a leather chair smoking a cigar dark room dramatic shadows wearing a black tuxedo`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Mafia boss sitting on a leather chair, smoking a cigar, dark room, dramatic shadows, wearing a black tuxedo, intense look. ${suffix}`,
    tags: ['mafia', 'boss', 'dark'],
    category: 'Cinematic',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 31000, likes: 13000, saves: 2900, comments: 420,
    createdAt: new Date(Date.now() - 13000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-14',
    title: 'Cute Astronaut',
    imageUrl: getImageUrl(`${KID_DESC} wearing a futuristic white astronaut suit floating in space earth in the background`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Wearing a futuristic white astronaut suit, floating in space, earth in the background, cinematic sci-fi lighting. ${suffix}`,
    tags: ['space', 'astronaut', 'scifi'],
    category: 'Fantasy',
    style: '3D Render',
    aspectRatio: '4:5',
    views: 22000, likes: 8500, saves: 1800, comments: 250,
    createdAt: new Date(Date.now() - 14000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-15',
    title: 'Holi Festival',
    imageUrl: getImageUrl(`${FEMALE_DESC} playing Holi face covered in vibrant gulal colors smiling festive background`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Playing Holi, face covered in vibrant gulal colors, smiling, festive background with colors in the air, joyful vibe. ${suffix}`,
    tags: ['holi', 'festival', 'colors'],
    category: 'Trending',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 29000, likes: 11500, saves: 2600, comments: 510,
    createdAt: new Date(Date.now() - 15000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-16',
    title: 'Snow Mountain Trekker',
    imageUrl: getImageUrl(`${MALE_DESC} trekking in the Himalayas wearing a heavy winter jacket and snow goggles snow-capped mountains`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Trekking in the Himalayas, wearing a heavy winter jacket and snow goggles, snow-capped mountains background, cold cinematic tones. ${suffix}`,
    tags: ['trekking', 'snow', 'mountains'],
    category: 'Trending',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 38000, likes: 16000, saves: 4200, comments: 730,
    createdAt: new Date(Date.now() - 16000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-17',
    title: 'K-Pop Idol',
    imageUrl: getImageUrl(`${BOY_DESC} as a K-Pop idol on stage holding a microphone trendy streetwear concert laser lights`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `K-Pop idol on stage, holding a microphone, trendy streetwear, concert laser lights, energetic crowd background. ${suffix}`,
    tags: ['kpop', 'idol', 'concert'],
    category: 'Trending',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 41000, likes: 18000, saves: 5100, comments: 880,
    createdAt: new Date(Date.now() - 17000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-18',
    title: 'Fairy Tale Princess',
    imageUrl: getImageUrl(`${FEMALE_DESC} as a Fairy tale princess in a magical forest wearing a glowing gown surrounded by fireflies`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Fairy tale princess in a magical forest, wearing a glowing gown, surrounded by fireflies, ethereal lighting. ${suffix}`,
    tags: ['princess', 'fairy', 'magical'],
    category: 'Fantasy',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 26000, likes: 10500, saves: 2400, comments: 390,
    createdAt: new Date(Date.now() - 18000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-19',
    title: 'Police Officer',
    imageUrl: getImageUrl(`${MALE_DESC} as an Indian police officer in uniform aviator sunglasses standing next to a police jeep`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Indian police officer in uniform, aviator sunglasses, standing next to a police jeep, authoritative pose, daylight. ${suffix}`,
    tags: ['police', 'officer', 'uniform'],
    category: 'Professions',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 19000, likes: 7800, saves: 1400, comments: 220,
    createdAt: new Date(Date.now() - 19000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-20',
    title: 'Doctor / Surgeon',
    imageUrl: getImageUrl(`${FEMALE_DESC} as a Professional doctor wearing a white coat and stethoscope modern hospital background`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Professional doctor wearing a white coat and stethoscope, modern hospital background, soft clean lighting. ${suffix}`,
    tags: ['doctor', 'hospital', 'medical'],
    category: 'Professions',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 35000, likes: 15000, saves: 3900, comments: 810,
    createdAt: new Date(Date.now() - 20000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-21',
    title: 'DJ at Tomorrowland',
    imageUrl: getImageUrl(`${BOY_DESC} performing as a DJ on a massive stage at Tomorrowland headphones on explosive fireworks`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `DJ performing on a massive stage at Tomorrowland, headphones on, hands in the air, explosive fireworks and laser lights. ${suffix}`,
    tags: ['dj', 'tomorrowland', 'party'],
    category: 'Trending',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 33000, likes: 13500, saves: 3100, comments: 580,
    createdAt: new Date(Date.now() - 21000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-22',
    title: 'Superhero Landing',
    imageUrl: getImageUrl(`${MALE_DESC} in a Superhero landing pose wearing a high-tech armored suit cracked ground cinematic dust`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Superhero landing pose, wearing a high-tech armored suit, cracked ground, cinematic dust and debris, epic lighting. ${suffix}`,
    tags: ['superhero', 'marvel', 'epic'],
    category: 'Fantasy',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 42000, likes: 18500, saves: 5300, comments: 920,
    createdAt: new Date(Date.now() - 22000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-23',
    title: 'Harry Potter Style',
    imageUrl: getImageUrl(`${KID_DESC} as a Wizard student wearing a Gryffindor robe holding a glowing magic wand Hogwarts castle`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Wizard student wearing a Gryffindor robe, holding a glowing magic wand, Hogwarts castle background, magical lighting. ${suffix}`,
    tags: ['wizard', 'magic', 'hogwarts'],
    category: 'Fantasy',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 16000, likes: 6200, saves: 1150, comments: 190,
    createdAt: new Date(Date.now() - 23000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-24',
    title: 'Luxury Yacht Party',
    imageUrl: getImageUrl(`${FEMALE_DESC} standing on a luxury yacht in Monaco holding a champagne glass elegant evening wear`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Standing on a luxury yacht in Monaco, holding a champagne glass, wearing elegant evening wear, ocean sunset. ${suffix}`,
    tags: ['yacht', 'luxury', 'party'],
    category: 'Luxury',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 21000, likes: 8800, saves: 1900, comments: 310,
    createdAt: new Date(Date.now() - 24000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-25',
    title: 'Street Dancer',
    imageUrl: getImageUrl(`${BOY_DESC} as a Hip-hop street dancer mid-air freeze frame wearing baggy clothes graffiti wall`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Hip-hop street dancer mid-air freeze frame, wearing baggy clothes and sneakers, graffiti wall background, urban lighting. ${suffix}`,
    tags: ['dance', 'hiphop', 'street'],
    category: 'Trending',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 36000, likes: 15500, saves: 4100, comments: 660,
    createdAt: new Date(Date.now() - 25000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-26',
    title: 'Coffee Shop Aesthetic',
    imageUrl: getImageUrl(`${FEMALE_DESC} sitting in a cozy aesthetic cafe reading a book drinking latte rain outside the window`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Sitting in a cozy aesthetic cafe, reading a book, drinking latte, rain outside the window, warm moody lighting. ${suffix}`,
    tags: ['cafe', 'aesthetic', 'coffee'],
    category: 'Trending',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 24000, likes: 9500, saves: 2000, comments: 370,
    createdAt: new Date(Date.now() - 26000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-27',
    title: 'Viking Warrior',
    imageUrl: getImageUrl(`${MALE_DESC} as a Fierce Viking warrior wearing fur armor holding an axe battlefield background`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Fierce Viking warrior, wearing fur armor, holding an axe, battlefield background, dramatic dark cinematic lighting. ${suffix}`,
    tags: ['viking', 'warrior', 'epic'],
    category: 'Fantasy',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 39000, likes: 17000, saves: 4800, comments: 840,
    createdAt: new Date(Date.now() - 27000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-28',
    title: 'Pilot in Cockpit',
    imageUrl: getImageUrl(`${FEMALE_DESC} as an Airline pilot sitting in a modern airplane cockpit wearing pilot uniform sky view`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Airline pilot sitting in a modern airplane cockpit, wearing pilot uniform and headset, sky view from window. ${suffix}`,
    tags: ['pilot', 'aviation', 'travel'],
    category: 'Professions',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 20000, likes: 8200, saves: 1600, comments: 290,
    createdAt: new Date(Date.now() - 28000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-29',
    title: 'Diwali Sparklers',
    imageUrl: getImageUrl(`${KID_DESC} holding glowing Diwali sparklers traditional kurta happy expression warm festive bokeh lights`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Holding glowing Diwali sparklers, traditional kurta, happy expression, warm festive bokeh lights background. ${suffix}`,
    tags: ['diwali', 'festival', 'lights'],
    category: 'Trending',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 14000, likes: 5500, saves: 950, comments: 150,
    createdAt: new Date(Date.now() - 29000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-30',
    title: 'Mumbai Local Train',
    imageUrl: getImageUrl(`${MALE_DESC} standing at Mumbai local train door wind blowing cinematic lighting intense expression`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Standing at Mumbai local train door, wind blowing, cinematic lighting, intense expression. ${suffix}`,
    tags: ['mumbai', 'train', 'cinematic'],
    category: 'Trending',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 18500, likes: 6200, saves: 1100, comments: 210,
    createdAt: new Date(Date.now() - 30000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-31',
    title: 'Gamer Setup',
    imageUrl: getImageUrl(`${BOY_DESC} sitting in a neon-lit gaming room wearing RGB headphones playing on a high-end PC`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Sitting in a neon-lit gaming room, wearing RGB headphones, playing on a high-end PC, focused expression. ${suffix}`,
    tags: ['gamer', 'gaming', 'neon'],
    category: 'Trending',
    style: 'Photorealistic',
    aspectRatio: '4:5',
    views: 22500, likes: 8900, saves: 1500, comments: 320,
    createdAt: new Date(Date.now() - 31000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  },
  {
    id: 'mock-32',
    title: 'Indian Army Soldier',
    imageUrl: getImageUrl(`${MALE_DESC} as an Indian Army Soldier in camouflage uniform holding a rifle rugged mountain terrain`),
    creator: { id: 'system', name: 'Qpixa AI', username: '@qpixa', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=qpixa', initials: 'QA', isVerified: true },
    prompt: `Indian Army Soldier in camouflage uniform, holding a rifle, rugged mountain terrain background, patriotic cinematic lighting. ${suffix}`,
    tags: ['army', 'soldier', 'patriotic'],
    category: 'Professions',
    style: 'Cinematic',
    aspectRatio: '4:5',
    views: 52000, likes: 24000, saves: 6100, comments: 1100,
    createdAt: new Date(Date.now() - 32000000).toISOString(),
    isLiked: false, isSaved: false, isShort: false, isMock: true
  }
];
