// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getEnv } from '@/lib/env';

// Safely get and validate the Supabase URL
let SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.VITE_SUPABASE_URL || '';
if (!SUPABASE_URL || !SUPABASE_URL.startsWith('http')) {
  SUPABASE_URL = 'https://placeholder-project.supabase.co';
}

const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || process.env.VITE_SUPABASE_ANON_KEY || 'placeholder-anon-key';

export const isPlaceholder = !SUPABASE_URL || SUPABASE_URL === 'https://placeholder-project.supabase.co' || SUPABASE_ANON_KEY === 'placeholder-anon-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const getSafeStorage = () => {
  if (typeof window === 'undefined') return undefined;
  try {
    const storage = window.localStorage;
    // Test access
    storage.getItem('test');
    return storage;
  } catch (e) {
    console.warn('localStorage access denied, probably in iframe. Auth state will not be persisted.');
    return undefined;
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: getSafeStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});