import { GoogleGenAI } from "@google/genai";

export default async function handler(req: any, res: any) {
  // Handle CORS if needed, but Vercel handles it for same-origin by default
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { prompt, model, image, config, type } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({ error: "GEMINI_API_KEY is not configured on the server." });
    }

    const ai = new GoogleGenAI({ apiKey });
    
    if (type === 'text') {
      const response = await ai.models.generateContent({
        model: model || "gemini-3-flash-preview",
        contents: prompt
      });
      return res.json({ text: response.text });
    }

    let contents;
    if (image) {
      const base64Data = image.split(',')[1];
      const mimeType = image.split(';')[0].split(':')[1] || 'image/png';
      contents = {
        parts: [
          { inlineData: { data: base64Data, mimeType } },
          { text: prompt }
        ]
      };
    } else {
      contents = {
        parts: [{ text: prompt }]
      };
    }

    const response = await ai.models.generateContent({
      model: model || "gemini-2.5-flash-image",
      contents,
      config: config || {
        imageConfig: {
          aspectRatio: "1:1",
          imageSize: "1K"
        }
      }
    });

    const part = response.candidates?.[0]?.content?.parts?.find(p => p.inlineData);
    if (part && part.inlineData) {
      const imageUrl = `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
      res.json({ imageUrl });
    } else {
      res.status(400).json({ error: "No image generated by AI" });
    }
  } catch (error: any) {
    console.error("Gemini Proxy Error:", error);
    res.status(500).json({ error: error.message || "Internal Server Error" });
  }
}
